name: mobile_probeaufgabe_lucas_schmidt
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  go_router:
  flutter_riverpod:
  hooks_riverpod:
  freezed_annotation:
  json_annotation:
  intl:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable:
  build_runner:
  freezed:

flutter:
  uses-material-design: true
